package com.github.martinfrank.games.chessmodel.message;

public enum MessageType {

    UNKNOWN ("UNKNOWN"),
    FS_WELCOME("FS_WELCOME"),

    FC_GET_PARTICIPATING_GAMES("FC_GET_PARTICIPATING_GAMES"),
    FS_SUBMIT_PARTICIPATING_GAMES("FS_SUBMIT_PARTICIPATING_GAMES"),
    FS_DECLINE_PARTICIPATING_GAMES("FS_DECLINE_PARTICIPATING_GAMES"),

    FC_GET_OPEN_GAMES("FC_GET_OPEN_GAMES"),
    FS_SUBMIT_OPEN_GAMES("FS_SUBMIT_OPEN_GAMES"),
    FS_DECLINE_OPEN_GAMES("FS_DECLINE_OPEN_GAMES"),

    FC_CREATE_GAME("FC_CREATE_GAME"),
    FS_SUBMIT_CREATED_GAME("FS_SUBMIT_CREATED_GAME"),
    FS_DECLINE_CREATE_GAME("FS_DECLINE_CREATE_GAME"),

    FS_SUBMIT_UPDATE_GAME("FS_SUBMIT_UPDATE_GAME"),

    FC_START_GAME("FS_START_GAME"),
    FS_SUBMIT_START_GAME("FS_SUBMIT_START_GAME"),
    FS_DECLINE_START_GAME("FS_DECLINE_START_GAME"),

    FC_LOGIN("FC_LOGIN"),
    FS_SUBMIT_LOGIN("FS_SUBMIT_LOGIN"),
    FS_SUBMIT_DISCONNECT("FS_SUBMIT_DISCONNECT"),

    FC_SELECT_COLOR("FC_SELECT_COLOR"),
    FS_DECLINE_SELECT_COLOR("FS_DECLINE_SELECT_COLOR"),
    FS_SUBMIT_SELECT_COLOR("FS_SUBMIT_SELECT_COLOR"),

    FC_SELECT_FIELD("FC_SELECT_FIELD"),
    FS_SUBMIT_SELECT_FIELD("FS_SUBMIT_SELECT_FIELD"),
    FS_DECLINE_SELECT_FIELD("FS_DECLINE_SELECT_FIELD"),


    FC_JOIN_GAME("FC_JOIN_GAME"),
    FS_CONFIRM_JOIN_GAME("FS_CONFIRM_JOIN_GAME"),
    FS_DECLINE_JOIN_GAME("FS_DECLINE_JOIN_GAME"),

    FC_GET_GAME_CONTENT("FC_GET_GAME_CONTENT"),
    FS_DECLINE_GAME_CONTENT("FS_DECLINE_GAME_CONTENT"),
    FS_SUBMIT_GAME_CONTENT("FS_SUBMIT_GAME_CONTENT"),

    ;

    public final String typeString;

    MessageType(String typeString){
        this.typeString = typeString;
    }
}
